### ISSUE TITLE
ReadScanline dont work with Tile Tiff

### ISSUE THREAD

**Issue by gabrielfelipeg** [simsab-ufcg/ndvi-finder#15]
Remove tile of tiffs should be a good option to solve this.

**Comment by Matheus7OP** [comment]
Solved [here](https://github.com/simsab-ufcg/ndvi-finder/commit/57ca4c851ed73f62af6c789f481026fff810fd00) and [here](https://github.com/simsab-ufcg/ndvi-finder/commit/26c29abcc257321dff8f91566500f84c17190f63)
